## Game Logs

In [1]:
import os
import pandas as pd

# Define the directory containing the scraped gamelog CSV files
gamelog_dir = "scraped_gamelogs"  # Change this if needed

# Initialize an empty list to store individual DataFrames
dataframes = []

# Loop through all year folders inside `scraped_gamelogs`
for year in os.listdir(gamelog_dir):
    year_path = os.path.join(gamelog_dir, year)

    # Ensure it's a directory
    if not os.path.isdir(year_path):
        continue

    # Loop through "reg" and "post" subfolders inside each year folder
    for season_type in ["reg", "post"]:
        season_path = os.path.join(year_path, season_type)

        if not os.path.exists(season_path):
            continue  # Skip if the subfolder doesn't exist

        # Load CSV files inside each season-type folder
        for filename in os.listdir(season_path):
            if filename.endswith(".csv"):
                file_path = os.path.join(season_path, filename)

                # Read the CSV file into a pandas DataFrame
                df = pd.read_csv(file_path)

                # Extract metadata from filename
                parts = filename.split("_")
                if len(parts) >= 3:
                    team = parts[1]  # Extract team code
                    season_year = parts[2]  # Extract year
                    df["Team"] = team
                    df["Season"] = season_year
                    df["SeasonType"] = season_type  # "reg" or "post"

                # Append the DataFrame to the list
                dataframes.append(df)

# Combine all DataFrames into one unified dataset
compiled_gamelogs = pd.concat(dataframes, ignore_index=True)

# Display the first few rows
print(compiled_gamelogs.head())

# Optionally, save the merged DataFrame for future use
compiled_gamelogs.to_csv("compiled_gamelogs.csv", index=False)

    Rk  Gtm        Date Unnamed: 3  Opp Rslt     Tm  Opp.1   OT    FG  ...  \
0  1.0  1.0  2022-04-17          @  MIA    L   91.0  115.0  NaN  29.0  ...
1  2.0  2.0  2022-04-19          @  MIA    L  105.0  115.0  NaN  41.0  ...
2  3.0  3.0  2022-04-22        NaN  MIA    W  111.0  110.0  NaN  41.0  ...
3  4.0  4.0  2022-04-24        NaN  MIA    L   86.0  110.0  NaN  30.0  ...
4  5.0  5.0  2022-04-26          @  MIA    L   94.0   97.0  NaN  31.0  ...

   DRB_opp  TRB_opp  AST_opp  STL_opp  BLK_opp  TOV_opp  PF_opp  Team  Season  \
0     36.0     40.0     35.0     12.0      3.0     15.0    22.0   ATL    2022
1     30.0     34.0     21.0      9.0      6.0     15.0    24.0   ATL    2022
2     34.0     45.0     30.0      6.0      3.0     15.0    23.0   ATL    2022
3     33.0     48.0     22.0      8.0      1.0      7.0    23.0   ATL    2022
4     26.0     33.0     19.0     12.0      2.0     14.0    25.0   ATL    2022

   SeasonType
0        post
1        post
2        post
3        post
4        post

[5 rows x 54 columns]

In [2]:
compiled_gamelogs

,Rk,Gtm,Date,Unnamed: 3,Opp,Rslt,Tm,Opp.1,OT,FG,...,DRB_opp,TRB_opp,AST_opp,STL_opp,BLK_opp,TOV_opp,PF_opp,Team,Season,SeasonType
0,1.0,1.0,2022-04-17,@,MIA,L,91.0,115.0,NaN,29.0,...,36.0,40.0,35.0,12.0,3.0,15.0,22.0,ATL,2022,post
1,2.0,2.0,2022-04-19,@,MIA,L,105.0,115.0,NaN,41.0,...,30.0,34.0,21.0,9.0,6.0,15.0,24.0,ATL,2022,post
2,3.0,3.0,2022-04-22,NaN,MIA,W,111.0,110.0,NaN,41.0,...,34.0,45.0,30.0,6.0,3.0,15.0,23.0,ATL,2022,post
3,4.0,4.0,2022-04-24,NaN,MIA,L,86.0,110.0,NaN,30.0,...,33.0,48.0,22.0,8.0,1.0,7.0,23.0,ATL,2022,post
4,5.0,5.0,2022-04-26,@,MIA,L,94.0,97.0,NaN,31.0,...,26.0,33.0,19.0,12.0,2.0,14.0,25.0,ATL,2022,post
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10585,1.0,1.0,2025-04-20,@,BOS,L,86.0,103.0,NaN,34.0,...,33.0,42.0,22.0,13.0,5.0,11.0,13.0,ORL,2025,post
10586,2.0,2.0,2025-04-23,@,BOS,L,100.0,109.0,NaN,39.0,...,33.0,46.0,17.0,6.0,4.0,11.0,19.0,ORL,2025,post
10587,3.0,3.0,2025-04-25,NaN,BOS,W,95.0,93.0,NaN,34.0,...,31.0,39.0,15.0,9.0,5.0,21.0,20.0,ORL,2025,post
10588,4.0,4.0,2025-04-27,NaN,BOS,L,98.0,107.0,NaN,38.0,...,35.0,46.0,17.0,7.0,7.0,11.0,17.0,ORL,2025,post
10589,5.0,5.0,2025-04-29,@,BOS,L,89.0,120.0,NaN,33.0,...,35.0,38.0,30.0,5.0,3.0,11.0,18.0,ORL,2025,post

In [3]:
# Get unique seasons
seasons = compiled_gamelogs["Season"].unique()

# Create individual DataFrames for each year and type
for season in seasons:
    globals()[f"gamelog_reg_{season}"] = compiled_gamelogs[
        (compiled_gamelogs["Season"] == season) & (compiled_gamelogs["SeasonType"] == "reg")
    ]
    
    globals()[f"gamelog_post_{season}"] = compiled_gamelogs[
        (compiled_gamelogs["Season"] == season) & (compiled_gamelogs["SeasonType"] == "post")
    ]

In [4]:
gamelog_post_2022

,Rk,Gtm,Date,Unnamed: 3,Opp,Rslt,Tm,Opp.1,OT,FG,...,DRB_opp,TRB_opp,AST_opp,STL_opp,BLK_opp,TOV_opp,PF_opp,Team,Season,SeasonType
0,1.0,1.0,2022-04-17,@,MIA,L,91.0,115.0,NaN,29.0,...,36.0,40.0,35.0,12.0,3.0,15.0,22.0,ATL,2022,post
1,2.0,2.0,2022-04-19,@,MIA,L,105.0,115.0,NaN,41.0,...,30.0,34.0,21.0,9.0,6.0,15.0,24.0,ATL,2022,post
2,3.0,3.0,2022-04-22,NaN,MIA,W,111.0,110.0,NaN,41.0,...,34.0,45.0,30.0,6.0,3.0,15.0,23.0,ATL,2022,post
3,4.0,4.0,2022-04-24,NaN,MIA,L,86.0,110.0,NaN,30.0,...,33.0,48.0,22.0,8.0,1.0,7.0,23.0,ATL,2022,post
4,5.0,5.0,2022-04-26,@,MIA,L,94.0,97.0,NaN,31.0,...,26.0,33.0,19.0,12.0,2.0,14.0,25.0,ATL,2022,post
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2663,2.0,2.0,2022-04-18,@,DAL,L,104.0,110.0,NaN,38.0,...,29.0,31.0,22.0,5.0,2.0,3.0,19.0,UTA,2022,post
2664,3.0,3.0,2022-04-21,NaN,DAL,L,118.0,126.0,NaN,39.0,...,26.0,32.0,24.0,10.0,1.0,9.0,32.0,UTA,2022,post
2665,4.0,4.0,2022-04-23,NaN,DAL,W,100.0,99.0,NaN,32.0,...,36.0,43.0,15.0,4.0,2.0,12.0,29.0,UTA,2022,post
2666,5.0,5.0,2022-04-25,@,DAL,L,77.0,102.0,NaN,29.0,...,38.0,49.0,16.0,6.0,1.0,11.0,18.0,UTA,2022,post
2667,6.0,6.0,2022-04-28,NaN,DAL,L,96.0,98.0,NaN,36.0,...,34.0,37.0,22.0,6.0,4.0,10.0,19.0,UTA,2022,post

In [5]:
compiled_gamelogs.sort_values(by='Date', ascending=True)

,Rk,Gtm,Date,Unnamed: 3,Opp,Rslt,Tm,Opp.1,OT,FG,...,DRB_opp,TRB_opp,AST_opp,STL_opp,BLK_opp,TOV_opp,PF_opp,Team,Season,SeasonType
758,1.0,1.0,2021-10-19,@,LAL,W,121.0,114.0,NaN,41.0,...,40.0,45.0,21.0,7.0,4.0,18.0,25.0,GSW,2022,reg
1332,1.0,1.0,2021-10-19,NaN,BRK,W,127.0,104.0,NaN,48.0,...,39.0,44.0,19.0,3.0,9.0,13.0,17.0,MIL,2022,reg
184,1.0,1.0,2021-10-19,@,MIL,L,104.0,127.0,NaN,37.0,...,41.0,54.0,25.0,8.0,9.0,8.0,19.0,BRK,2022,reg
1086,1.0,1.0,2021-10-19,NaN,GSW,L,114.0,121.0,NaN,45.0,...,41.0,50.0,30.0,9.0,2.0,17.0,18.0,LAL,2022,reg
2316,1.0,1.0,2021-10-20,NaN,OKC,W,107.0,86.0,NaN,40.0,...,35.0,50.0,19.0,4.0,2.0,15.0,15.0,UTA,2022,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NYK,2025,post
10552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NYK,2025,post
10563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OKC,2025,post
10571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OKC,2025,post
10577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OKC,2025,post

In [6]:
# Drop rows where more than 50% of the columns are NaN
compiled_gamelogs = compiled_gamelogs[compiled_gamelogs.isnull().mean(axis=1) < 0.5]

# Optional: reset index
compiled_gamelogs.reset_index(drop=True, inplace=True)

# Check how many rows were dropped
print(f"✅ Remaining rows after drop: {compiled_gamelogs.shape[0]}")

✅ Remaining rows after drop: 10533

In [7]:
# Create a normalized matchup key (sorted tuple of team and opponent)
compiled_gamelogs['MatchKey'] = compiled_gamelogs.apply(
    lambda row: tuple(sorted([row['Team'], row['Opp']])) + (row['Date'],), axis=1
)

# Sort by that composite key
compiled_gamelogs = compiled_gamelogs.sort_values(by='MatchKey').reset_index(drop=True)

# Drop the helper column if you don't need it
compiled_gamelogs.drop(columns='MatchKey', inplace=True)

# Optional: preview grouped games
print(compiled_gamelogs[['Team', 'Opp', 'Date']].head(10))

  Team  Opp        Date
0  BOS  ATL  2021-11-17
1  ATL  BOS  2021-11-17
2  ATL  BOS  2022-01-28
3  BOS  ATL  2022-01-28
4  ATL  BOS  2022-02-13
5  BOS  ATL  2022-02-13
6  ATL  BOS  2022-03-01
7  BOS  ATL  2022-03-01
8  BOS  ATL  2022-11-16
9  ATL  BOS  2022-11-16

C:\Users\lukes\AppData\Local\Temp\ipykernel_25388\2269825219.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  compiled_gamelogs['MatchKey'] = compiled_gamelogs.apply(

In [8]:
def create_game_id(df):
    df = df.copy()
    df['GameID'] = df.apply(lambda row: "_".join(sorted([row['Team'], row['Opp']])) + "_" + row['Date'], axis=1)
    return df

In [9]:
def create_matchup_table(df):
    df = create_game_id(df)

    # Team perspective
    team_df = df.copy()
    team_df.columns = [f"Team_{col}" if col not in ['GameID'] else col for col in team_df.columns]

    # Opponent perspective
    opp_df = df.copy()
    opp_df.columns = [f"Opp_{col}" if col not in ['GameID'] else col for col in opp_df.columns]

    # Merge both perspectives on GameID
    matchup_df = pd.merge(team_df, opp_df, on='GameID')

    # Drop duplicate matchups (keep one per pair)
    matchup_df = matchup_df[matchup_df['Team_Team'] != matchup_df['Opp_Team']]
    matchup_df = matchup_df.drop_duplicates(subset='GameID').reset_index(drop=True)

    return matchup_df

In [10]:
matchup_df = create_matchup_table(compiled_gamelogs)

# Preview
print(matchup_df[['GameID', 'Team_Team', 'Team_Opp', 'Team_Date', 'Team_Rslt', 'Opp_Rslt']].head())

               GameID Team_Team Team_Opp   Team_Date Team_Rslt Opp_Rslt
0  ATL_BOS_2021-11-17       BOS      ATL  2021-11-17         L        W
1  ATL_BOS_2022-01-28       ATL      BOS  2022-01-28         W        L
2  ATL_BOS_2022-02-13       ATL      BOS  2022-02-13         L        W
3  ATL_BOS_2022-03-01       ATL      BOS  2022-03-01         L        W
4  ATL_BOS_2022-11-16       BOS      ATL  2022-11-16         W        L

In [11]:
print(f"Total Games: {compiled_gamelogs.shape[0]}")

Total Games: 10533

In [12]:
reg_count = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "reg"].shape[0]
post_count = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "post"].shape[0]

print(f"📅 Regular season games: {reg_count}")
print(f"🏆 Playoff games: {post_count}")

📅 Regular season games: 9840
🏆 Playoff games: 693

In [13]:
# Filter playoff games
playoff_games = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "post"]

# Create a game ID that accounts for both teams + date
playoff_games["GameID"] = playoff_games.apply(
    lambda row: "_".join(sorted([row["Team"], row["Opp"]])) + "_" + row["Date"], axis=1
)

# Count the frequency of each GameID
game_counts = playoff_games["GameID"].value_counts()

# Find odd-count games (should all be 2)
odd_games = game_counts[game_counts != 2]

print(f"🔍 Mismatched playoff entries found: {len(odd_games)}")
print(odd_games)

🔍 Mismatched playoff entries found: 19
GameID
ATL_MIA_2022-04-19    3
ATL_MIA_2022-04-22    3
ATL_MIA_2022-04-24    3
ATL_MIA_2022-04-26    3
DEN_LAC_2025-04-24    3
DEN_LAC_2025-04-26    3
DEN_LAC_2025-04-29    3
DEN_LAC_2025-05-01    3
DEN_LAC_2025-05-03    3
DEN_LAC_2025-04-19    3
DEN_LAC_2025-04-21    3
DEN_OKC_2025-05-05    3
DEN_OKC_2025-05-07    3
DEN_OKC_2025-05-09    3
DEN_OKC_2025-05-11    3
DEN_OKC_2025-05-13    3
DEN_OKC_2025-05-15    3
DEN_OKC_2025-05-18    3
ATL_MIA_2022-04-17    3
Name: count, dtype: int64

C:\Users\lukes\AppData\Local\Temp\ipykernel_25388\2797426833.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playoff_games["GameID"] = playoff_games.apply(

In [14]:
mask = (compiled_gamelogs["Date"] == "2022-04-17") & (compiled_gamelogs["SeasonType"] == "post") & (compiled_gamelogs["Team"].isin(["ATL", "MIA"])) & (compiled_gamelogs["Opp"].isin(["ATL", "MIA"]))

In [15]:
compiled_gamelogs.drop_duplicates(subset=["Team", "Opp", "Date", "SeasonType"], inplace=True)

In [16]:
# Recreate GameID column
compiled_gamelogs["GameID"] = compiled_gamelogs.apply(
    lambda row: "_".join(sorted([row["Team"], row["Opp"]])) + "_" + row["Date"], axis=1
)

# Check for mismatches again
playoff_games = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "post"]
print(playoff_games["GameID"].value_counts()[lambda x: x != 2])

Series([], Name: count, dtype: int64)

In [17]:
reg_count = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "reg"].shape[0]
post_count = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "post"].shape[0]

print(f"📅 Regular season games: {reg_count}")
print(f"🏆 Playoff games: {post_count}")

📅 Regular season games: 9840
🏆 Playoff games: 674

In [18]:
total_games = compiled_gamelogs.shape[0] // 2
print(f"🏀 Unique NBA games represented: {total_games}")

🏀 Unique NBA games represented: 5257

In [19]:
total_post_games = compiled_gamelogs[compiled_gamelogs["SeasonType"] == "post"].shape[0] // 2
print(total_post_games)

337

## Advanced Game Logs

In [20]:
import os
import pandas as pd

# Define the directory containing the scraped gamelog CSV files
advanced_gamelog_dir = "scraped_gamelogs_advanced"  # Change this if needed

# Initialize an empty list to store individual DataFrames
dataframes = []

# Loop through all year folders inside `scraped_gamelogs`
for year in os.listdir(advanced_gamelog_dir):
    year_path = os.path.join(advanced_gamelog_dir, year)

    # Ensure it's a directory
    if not os.path.isdir(year_path):
        continue

    # Loop through "reg" and "post" subfolders inside each year folder
    for season_type in ["reg", "post"]:
        season_path = os.path.join(year_path, season_type)

        if not os.path.exists(season_path):
            continue  # Skip if the subfolder doesn't exist

        # Load CSV files inside each season-type folder
        for filename in os.listdir(season_path):
            if filename.endswith(".csv"):
                file_path = os.path.join(season_path, filename)

                # Read the CSV file into a pandas DataFrame
                df = pd.read_csv(file_path)

                # Extract metadata from filename
                parts = filename.split("_")
                if len(parts) >= 3:
                    team = parts[2]  # Extract team code
                    season_year = parts[3]  # Extract year
                    df["Team"] = team
                    df["Season"] = season_year
                    df["SeasonType"] = season_type  # "reg" or "post"

                # Append the DataFrame to the list
                dataframes.append(df)

# Combine all DataFrames into one unified dataset
compiled_advanced_gamelogs = pd.concat(dataframes, ignore_index=True)

# Display the first few rows
print(compiled_advanced_gamelogs.head())

# Optionally, save the merged DataFrame for future use
compiled_advanced_gamelogs.to_csv("compiled_advanced_gamelogs.csv", index=False)

    Rk  Gtm        Date Unnamed: 3  Opp Rslt     Tm  Opp.1   OT   ORtg  ...  \
0  1.0  1.0  2021-10-21        NaN  DAL    W  113.0   87.0  NaN  109.9  ...
1  2.0  2.0  2021-10-23          @  CLE    L   95.0  101.0  NaN   99.3  ...
2  3.0  3.0  2021-10-25        NaN  DET    W  122.0  104.0  NaN  121.3  ...
3  4.0  4.0  2021-10-27          @  NOP    W  102.0   99.0  NaN  109.6  ...
4  5.0  5.0  2021-10-28          @  WAS    L  111.0  122.0  NaN  110.2  ...

   TOV%  ORB%  FT/FGA  eFG%.1  TOV%.1  ORB%.1  FT/FGA.1  Team  Season  \
0  11.7  13.0   0.085   0.403    13.2    16.9     0.129   ATL    2022
1   7.9  28.8   0.091   0.455     9.0    24.5     0.225   ATL    2022
2  13.9  28.6   0.200   0.489    12.4    22.0     0.165   ATL    2022
3   9.6  37.5   0.146   0.489     9.3    20.9     0.086   ATL    2022
4  12.1  14.0   0.102   0.530     7.7    27.5     0.172   ATL    2022

   SeasonType
0         reg
1         reg
2         reg
3         reg
4         reg

[5 rows x 30 columns]

In [21]:
compiled_advanced_gamelogs

,Rk,Gtm,Date,Unnamed: 3,Opp,Rslt,Tm,Opp.1,OT,ORtg,...,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,ORB%.1,FT/FGA.1,Team,Season,SeasonType
0,1.0,1.0,2021-10-21,NaN,DAL,W,113.0,87.0,NaN,109.9,...,11.7,13.0,0.085,0.403,13.2,16.9,0.129,ATL,2022,reg
1,2.0,2.0,2021-10-23,@,CLE,L,95.0,101.0,NaN,99.3,...,7.9,28.8,0.091,0.455,9.0,24.5,0.225,ATL,2022,reg
2,3.0,3.0,2021-10-25,NaN,DET,W,122.0,104.0,NaN,121.3,...,13.9,28.6,0.200,0.489,12.4,22.0,0.165,ATL,2022,reg
3,4.0,4.0,2021-10-27,@,NOP,W,102.0,99.0,NaN,109.6,...,9.6,37.5,0.146,0.489,9.3,20.9,0.086,ATL,2022,reg
4,5.0,5.0,2021-10-28,@,WAS,L,111.0,122.0,NaN,110.2,...,12.1,14.0,0.102,0.530,7.7,27.5,0.172,ATL,2022,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10565,1.0,1.0,2025-04-20,@,BOS,L,86.0,103.0,NaN,98.5,...,14.9,28.3,0.099,0.549,10.9,24.3,0.159,ORL,2025,post
10566,2.0,2.0,2025-04-23,@,BOS,L,100.0,109.0,NaN,111.5,...,7.0,17.5,0.183,0.525,10.4,32.5,0.313,ORL,2025,post
10567,3.0,3.0,2025-04-25,NaN,BOS,W,95.0,93.0,NaN,103.2,...,12.9,32.6,0.229,0.507,20.1,22.9,0.243,ORL,2025,post
10568,4.0,4.0,2025-04-27,NaN,BOS,L,98.0,107.0,NaN,105.1,...,9.4,16.7,0.159,0.494,10.7,26.2,0.385,ORL,2025,post
10569,5.0,5.0,2025-04-29,@,BOS,L,89.0,120.0,NaN,96.5,...,10.9,30.0,0.170,0.651,11.3,9.4,0.276,ORL,2025,post

In [22]:
# Get unique seasons from the team stats
unique_seasons = compiled_advanced_gamelogs["Season"].unique()

# For each season, filter out regular season and postseason data
# and assign them as new global DataFrames with unique variable names.
for season in unique_seasons:
    # Create a DataFrame for regular season stats for this season
    globals()[f"gamelog_adv_reg_{season}"] = compiled_advanced_gamelogs[
        (compiled_advanced_gamelogs["Season"] == season) & (compiled_advanced_gamelogs["SeasonType"] == "reg")
    ]
    
    # Create a DataFrame for postseason stats for this season
    globals()[f"gamelog_adv_post_{season}"] = compiled_advanced_gamelogs[
        (compiled_advanced_gamelogs["Season"] == season) & (compiled_advanced_gamelogs["SeasonType"] == "post")
    ]

In [23]:
gamelog_adv_post_2022

,Rk,Gtm,Date,Unnamed: 3,Opp,Rslt,Tm,Opp.1,OT,ORtg,...,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,ORB%.1,FT/FGA.1,Team,Season,SeasonType
2460,1.0,1.0,2022-04-17,@,MIA,L,91.0,115.0,NaN,93.7,...,17.2,18.2,0.307,0.634,14.3,11.8,0.134,ATL,2022,post
2461,2.0,2.0,2022-04-19,@,MIA,L,105.0,115.0,NaN,103.4,...,16.9,18.9,0.126,0.570,14.1,10.8,0.316,ATL,2022,post
2462,3.0,3.0,2022-04-22,NaN,MIA,W,111.0,110.0,NaN,114.3,...,11.0,12.8,0.213,0.516,13.0,26.2,0.151,ATL,2022,post
2463,4.0,4.0,2022-04-24,NaN,MIA,L,86.0,110.0,NaN,98.4,...,15.2,25.0,0.147,0.505,6.5,33.3,0.185,ATL,2022,post
2464,5.0,5.0,2022-04-26,@,MIA,L,94.0,97.0,NaN,101.6,...,18.0,31.6,0.324,0.494,13.3,18.9,0.195,ATL,2022,post
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,2.0,2.0,2022-04-18,@,DAL,L,104.0,110.0,NaN,118.2,...,9.9,27.5,0.207,0.602,3.3,4.9,0.120,UTA,2022,post
2644,3.0,3.0,2022-04-21,NaN,DAL,L,118.0,126.0,NaN,122.8,...,14.4,3.7,0.449,0.602,8.5,16.2,0.313,UTA,2022,post
2645,4.0,4.0,2022-04-23,NaN,DAL,W,100.0,99.0,NaN,110.9,...,7.6,26.5,0.329,0.526,12.1,17.5,0.234,UTA,2022,post
2646,5.0,5.0,2022-04-25,@,DAL,L,77.0,102.0,NaN,84.6,...,13.1,15.6,0.208,0.506,10.5,25.0,0.188,UTA,2022,post
2647,6.0,6.0,2022-04-28,NaN,DAL,L,96.0,98.0,NaN,105.9,...,10.6,24.4,0.179,0.556,10.5,7.5,0.113,UTA,2022,post

## Team Stats

In [24]:
import os
import pandas as pd

team_stats_dir = "scraped_team_stats/"  # Change this if needed

# Initialize an empty list to store individual DataFrames
dataframes = []

# Loop through all year folders inside `scraped_gamelogs`
for year in os.listdir(team_stats_dir):
    year_path = os.path.join(team_stats_dir, year)

    # Ensure it's a directory
    if not os.path.isdir(year_path):
        continue

    # Loop through "reg" and "post" subfolders inside each year folder
    for season_type in ["reg", "post"]:
        season_path = os.path.join(year_path, season_type)

        if not os.path.exists(season_path):
            continue  # Skip if the subfolder doesn't exist

        # Load CSV files inside each season-type folder
        for filename in os.listdir(season_path):
            if filename.endswith(".csv"):
                file_path = os.path.join(season_path, filename)

                # Read the CSV file into a pandas DataFrame
                df = pd.read_csv(file_path)

                # Extract metadata from filename
                parts = filename.split("_")
                if len(parts) >= 3:
                    team = parts[0]  # Extract team code
                    season_year = parts[1]  # Extract year
                    df["Team"] = team
                    df["Season"] = season_year
                    df["SeasonType"] = season_type  # "reg" or "post"

                # Append the DataFrame to the list
                dataframes.append(df)

# Combine all DataFrames into one unified dataset
compiled_team_stats = pd.concat(dataframes, ignore_index=True)

# Display the first few rows
print(compiled_team_stats.head())

# Optionally, save the merged DataFrame for future use
compiled_team_stats.to_csv("compiled_team_stats.csv", index=False)

   Rk              Player  Age Pos   G  GS    MP   FG   FGA    FG%  ...  AST  \
0   1          Trae Young   23  PG  76  76  34.9  9.4  20.3  0.460  ...  9.7
1   2        John Collins   24  PF  54  53  30.8  6.3  11.9  0.526  ...  1.8
2   3     De'Andre Hunter   24  SF  53  52  29.8  4.8  10.8  0.442  ...  1.3
3   4       Kevin Huerter   23  SF  74  60  29.6  4.7  10.3  0.454  ...  2.7
4   5  Bogdan BogdanoviÄ   29  SG  63  27  29.3  5.4  12.6  0.431  ...  3.1

   STL  BLK  TOV   PF   PTS   Awards  Team  Season  SeasonType
0  0.9  0.1  4.0  1.7  28.4  AS,NBA3   ATL    2022         reg
1  0.6  1.0  1.1  3.0  16.2      NaN   ATL    2022         reg
2  0.7  0.4  1.3  2.9  13.4      NaN   ATL    2022         reg
3  0.7  0.4  1.2  2.5  12.1      NaN   ATL    2022         reg
4  1.1  0.2  1.1  2.1  15.1   6MOY-6   ATL    2022         reg

[5 rows x 33 columns]

In [25]:
compiled_team_stats

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Awards,Team,Season,SeasonType
0,1,Trae Young,23,PG,76,76,34.9,9.4,20.3,0.460,...,9.7,0.9,0.1,4.0,1.7,28.4,"AS,NBA3",ATL,2022,reg
1,2,John Collins,24,PF,54,53,30.8,6.3,11.9,0.526,...,1.8,0.6,1.0,1.1,3.0,16.2,NaN,ATL,2022,reg
2,3,De'Andre Hunter,24,SF,53,52,29.8,4.8,10.8,0.442,...,1.3,0.7,0.4,1.3,2.9,13.4,NaN,ATL,2022,reg
3,4,Kevin Huerter,23,SF,74,60,29.6,4.7,10.3,0.454,...,2.7,0.7,0.4,1.2,2.5,12.1,NaN,ATL,2022,reg
4,5,Bogdan BogdanoviÄ,29,SG,63,27,29.3,5.4,12.6,0.431,...,3.1,1.1,0.2,1.1,2.1,15.1,6MOY-6,ATL,2022,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3497,9,Cole Anthony,24,PG,5,0,10.2,0.8,2.8,0.286,...,1.2,0.0,0.2,1.8,2.4,2.2,NaN,ORL,2025,post
3498,10,Caleb Houstan,22,SF,5,0,9.4,0.4,2.8,0.143,...,0.2,0.0,0.2,0.4,0.6,1.2,NaN,ORL,2025,post
3499,11,Jett Howard,21,SF,1,0,4.0,2.0,2.0,1.000,...,0.0,0.0,0.0,0.0,1.0,6.0,NaN,ORL,2025,post
3500,12,Goga Bitadze,25,C,3,0,3.7,0.3,0.3,1.000,...,0.3,0.0,0.3,0.0,2.0,0.7,NaN,ORL,2025,post
3501,13,Tristan Da Silva,23,SF,2,0,2.5,0.0,0.5,0.000,...,0.5,0.0,0.0,1.0,0.0,0.0,NaN,ORL,2025,post

In [26]:
# Get unique seasons from the team stats
unique_seasons = compiled_team_stats["Season"].unique()

# For each season, filter out regular season and postseason data
# and assign them as new global DataFrames with unique variable names.
for season in unique_seasons:
    # Create a DataFrame for regular season stats for this season
    globals()[f"team_stats_reg_{season}"] = compiled_team_stats[
        (compiled_team_stats["Season"] == season) & (compiled_team_stats["SeasonType"] == "reg")
    ]
    
    # Create a DataFrame for postseason stats for this season
    globals()[f"team_stats_post_{season}"] = compiled_team_stats[
        (compiled_team_stats["Season"] == season) & (compiled_team_stats["SeasonType"] == "post")
    ]

team_stats_reg_2022

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Awards,Team,Season,SeasonType
0,1,Trae Young,23,PG,76,76,34.9,9.4,20.3,0.460,...,9.7,0.9,0.1,4.0,1.7,28.4,"AS,NBA3",ATL,2022,reg
1,2,John Collins,24,PF,54,53,30.8,6.3,11.9,0.526,...,1.8,0.6,1.0,1.1,3.0,16.2,NaN,ATL,2022,reg
2,3,De'Andre Hunter,24,SF,53,52,29.8,4.8,10.8,0.442,...,1.3,0.7,0.4,1.3,2.9,13.4,NaN,ATL,2022,reg
3,4,Kevin Huerter,23,SF,74,60,29.6,4.7,10.3,0.454,...,2.7,0.7,0.4,1.2,2.5,12.1,NaN,ATL,2022,reg
4,5,Bogdan BogdanoviÄ,29,SG,63,27,29.3,5.4,12.6,0.431,...,3.1,1.1,0.2,1.1,2.1,15.1,6MOY-6,ATL,2022,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
710,25,Alize Johnson,25,PF,3,0,6.0,0.7,2.0,0.333,...,0.0,0.0,0.0,1.0,0.0,1.3,NaN,WAS,2022,reg
711,26,Cassius Winston,23,PG,7,0,5.6,0.6,1.6,0.364,...,1.0,0.0,0.0,0.4,1.3,2.0,NaN,WAS,2022,reg
712,27,Jordan Goodwin,23,SG,2,0,3.0,0.0,1.5,0.000,...,0.0,0.0,0.0,0.0,0.5,0.0,NaN,WAS,2022,reg
713,28,Jaime Echenique,24,C,1,0,3.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,WAS,2022,reg
714,29,Joel Ayayi,21,SG,7,0,2.9,0.1,0.9,0.167,...,0.6,0.0,0.0,0.0,0.0,0.3,NaN,WAS,2022,reg

In [27]:
# Group by season and count unique player names
player_counts = compiled_team_stats.groupby("Season")["Player"].nunique()

# Display results
print("🧑‍🏀 Number of unique players per season in team stats:")
print(player_counts.sort_index())

🧑‍🏀 Number of unique players per season in team stats:
Season
2022    606
2023    541
2024    572
2025    569
Name: Player, dtype: int64

In [28]:
unique_players_total = compiled_team_stats["Player"].nunique()
print(f"🧑‍💻 Total unique players scraped: {unique_players_total}")

🧑‍💻 Total unique players scraped: 926

## Advanced Team Stats

In [29]:
advanced_team_stats_dir = "scraped_team_stats_advanced/"  # Change this if needed

# Initialize an empty list to store individual DataFrames
dataframes = []

# Loop through all year folders inside `scraped_gamelogs`
for year in os.listdir(advanced_team_stats_dir):
    year_path = os.path.join(advanced_team_stats_dir, year)

    # Ensure it's a directory
    if not os.path.isdir(year_path):
        continue

    # Loop through "reg" and "post" subfolders inside each year folder
    for season_type in ["reg", "post"]:
        season_path = os.path.join(year_path, season_type)

        if not os.path.exists(season_path):
            continue  # Skip if the subfolder doesn't exist

        # Load CSV files inside each season-type folder
        for filename in os.listdir(season_path):
            if filename.endswith(".csv"):
                file_path = os.path.join(season_path, filename)

                # Read the CSV file into a pandas DataFrame
                df = pd.read_csv(file_path)

                # Extract metadata from filename
                parts = filename.split("_")
                if len(parts) >= 3:
                    team = parts[0]  # Extract team code
                    season_year = parts[1]  # Extract year
                    df["Team"] = team
                    df["Season"] = season_year
                    df["SeasonType"] = season_type  # "reg" or "post"

                # Append the DataFrame to the list
                dataframes.append(df)

# Combine all DataFrames into one unified dataset
compiled_team_stats_advanced = pd.concat(dataframes, ignore_index=True)

# Display the first few rows
print(compiled_team_stats_advanced.head())

# Optionally, save the merged DataFrame for future use
compiled_team_stats_advanced.to_csv("compiled_team_stats_advanced.csv", index=False)

   Rk              Player  Age Pos   G  GS    MP   PER    TS%   3PAr  ...  \
0   1          Trae Young   23  PG  76  76  2652  25.4  0.603  0.395  ...
1   2       Kevin Huerter   23  SF  74  60  2188  11.9  0.570  0.541  ...
2   3        Clint Capela   27   C  74  73  2042  21.4  0.604  0.002  ...
3   4  Bogdan BogdanoviÄ   29  SG  63  27  1848  15.4  0.562  0.578  ...
4   5    Danilo Gallinari   33  PF  66  18  1672  14.3  0.579  0.492  ...

     WS  WS/48  OBPM  DBPM  BPM  VORP   Awards  Team  Season  SeasonType
0  10.0  0.181   7.1  -2.0  5.2   4.8  AS,NBA3   ATL    2022         reg
1   2.8  0.062  -0.5  -0.7 -1.2   0.4      NaN   ATL    2022         reg
2   8.3  0.195   2.1  -0.1  2.0   2.1      NaN   ATL    2022         reg
3   3.7  0.095   1.5  -0.2  1.3   1.5   6MOY-6   ATL    2022         reg
4   3.6  0.105   1.0  -1.2 -0.2   0.8      NaN   ATL    2022         reg

[5 rows x 31 columns]

In [30]:
compiled_team_stats_advanced

,Rk,Player,Age,Pos,G,GS,MP,PER,TS%,3PAr,...,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards,Team,Season,SeasonType
0,1,Trae Young,23,PG,76,76,2652,25.4,0.603,0.395,...,10.0,0.181,7.1,-2.0,5.2,4.8,"AS,NBA3",ATL,2022,reg
1,2,Kevin Huerter,23,SF,74,60,2188,11.9,0.570,0.541,...,2.8,0.062,-0.5,-0.7,-1.2,0.4,NaN,ATL,2022,reg
2,3,Clint Capela,27,C,74,73,2042,21.4,0.604,0.002,...,8.3,0.195,2.1,-0.1,2.0,2.1,NaN,ATL,2022,reg
3,4,Bogdan BogdanoviÄ,29,SG,63,27,1848,15.4,0.562,0.578,...,3.7,0.095,1.5,-0.2,1.3,1.5,6MOY-6,ATL,2022,reg
4,5,Danilo Gallinari,33,PF,66,18,1672,14.3,0.579,0.492,...,3.6,0.105,1.0,-1.2,-0.2,0.8,NaN,ATL,2022,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3497,9,Cole Anthony,24,PG,5,0,51,-4.3,0.349,0.429,...,-0.3,-0.275,-13.4,-3.0,-16.4,-0.2,NaN,ORL,2025,post
3498,10,Caleb Houstan,22,SF,5,0,47,-4.1,0.214,0.714,...,-0.2,-0.213,-9.0,-3.6,-12.6,-0.1,NaN,ORL,2025,post
3499,11,Goga Bitadze,25,C,3,0,11,9.2,1.000,0.000,...,0.0,0.191,-10.7,6.3,-4.4,0.0,NaN,ORL,2025,post
3500,12,Tristan Da Silva,23,SF,2,0,5,-11.8,0.000,1.000,...,-0.1,-0.628,-22.2,-0.5,-22.6,0.0,NaN,ORL,2025,post
3501,13,Jett Howard,21,SF,1,0,4,61.7,1.500,1.000,...,0.0,0.320,38.1,9.4,47.5,0.0,NaN,ORL,2025,post

In [31]:
# Get unique seasons from the team stats
unique_seasons = compiled_team_stats_advanced["Season"].unique()

# For each season, filter out regular season and postseason data
# and assign them as new global DataFrames with unique variable names.
for season in unique_seasons:
    # Create a DataFrame for regular season stats for this season
    globals()[f"advanced_team_stats_reg_{season}"] = compiled_team_stats[
        (compiled_team_stats["Season"] == season) & (compiled_team_stats["SeasonType"] == "reg")
    ]
    
    # Create a DataFrame for postseason stats for this season
    globals()[f"advanced_team_stats_post_{season}"] = compiled_team_stats[
        (compiled_team_stats["Season"] == season) & (compiled_team_stats["SeasonType"] == "post")
    ]

In [32]:
advanced_team_stats_post_2022

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Awards,Team,Season,SeasonType
715,1,Trae Young,23,PG,5,5,37.2,4.4,13.8,0.319,...,6.0,0.6,0.0,6.2,2.6,15.4,NaN,ATL,2022,post
716,2,De'Andre Hunter,24,SF,5,5,35.0,7.8,14.0,0.557,...,0.6,0.8,0.2,2.2,4.0,21.2,NaN,ATL,2022,post
717,3,Kevin Huerter,23,SF,5,5,30.8,3.4,9.4,0.362,...,3.8,1.2,0.6,2.2,3.0,9.2,NaN,ATL,2022,post
718,4,Delon Wright,29,SG,5,0,27.4,3.0,5.8,0.517,...,2.8,0.8,0.2,1.0,0.4,8.2,NaN,ATL,2022,post
719,5,Bogdan BogdanoviÄ,29,SG,4,0,26.8,5.0,12.3,0.408,...,3.0,0.3,0.3,1.0,3.0,14.3,NaN,ATL,2022,post
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,8,Hassan Whiteside,32,C,6,0,10.8,0.8,2.0,0.417,...,0.0,0.3,1.3,0.0,1.5,1.8,NaN,UTA,2022,post
928,9,Juancho HernangÃ³mez,26,PF,6,0,9.3,0.8,3.0,0.278,...,0.8,0.3,0.0,0.3,0.7,2.3,NaN,UTA,2022,post
929,10,Eric Paschall,25,PF,4,0,6.0,0.8,1.5,0.500,...,0.0,0.3,0.0,0.0,0.8,2.0,NaN,UTA,2022,post
930,11,Nickeil Alexander-Walker,23,SG,1,0,5.0,2.0,2.0,1.000,...,1.0,1.0,0.0,0.0,0.0,5.0,NaN,UTA,2022,post
931,12,Jared Butler,21,SG,1,0,5.0,0.0,2.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,UTA,2022,post

In [36]:
import zipfile

with zipfile.ZipFile("compiled_gamelogs.zip", "w") as zipf:
    zipf.write("compiled_gamelogs.csv")

with zipfile.ZipFile("compiled_advanced_gamelogs.csv.zip", "w") as zipf:
    zipf.write("compiled_advanced_gamelogs.csv")

with zipfile.ZipFile("compiled_team_stats_advanced.csv.zip", "w") as zipf:
    zipf.write("compiled_team_stats_advanced.csv")

with zipfile.ZipFile("compiled_team_stats.csv.zip", "w") as zipf:
    zipf.write("compiled_team_stats.csv")